FROM maven:openjdk AS builder
COPY src /opt/src
COPY pom.xml /opt
WORKDIR /opt
RUN mvn -f /opt/pom.xml clean compile assembly:single

FROM  openjdk:8u302-jre
COPY --from=builder /opt/target/*.jar /opt/assets/ignite.jar
WORKDIR /opt/assets
ENV JAVA_OPTS_GC="-server -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC"
ENV JAVA_OPTS="-Xms256m -Xmx256m"
EXPOSE 50000
EXPOSE 50001
EXPOSE 10800 11211 47100 47500 49112 8080
CMD java $JAVA_OPTS_GC $JAVA_OPTS -jar ignite.jar
