version: "3.2"

networks:
  ignite-net:

services:
  ignite-server:
    image: rainbow-storage:1.3.1-test
    hostname: rainbow-storage-server
    networks:
      - ignite-net
    environment:
      NODE: SERVER
      DISCOVERY: ignite-server
      HOSTNAME: ignite-server
    volumes:
#      - "/opt/ignite-log4j.xml:/opt/assets/ignite-log4j.xml"
      - ./data:/opt/assets/ignite
    ports:
      - target: 50000
        published: 50000
        protocol: tcp
        mode: host
      - target: 10800
        published: 10800
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
