version: "3.2"

networks:
  ignite-net:

services:

  ignite-server:
    image: rainbow-storage:1.2.2
    hostname: server-{{ .Task.Slot }}
    networks:
      - ignite-net
    environment:
      NODE: SERVER
      DISCOVERY: server-1
      PERSISTENCE: "true"
      APP_CACHE: "true"
    ports:
      - target: 50000
        published: 50000
        protocol: tcp
        mode: host
      - target: 10800
        published: 10800
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  ignite-client:
    image: rainbow-storage:1.2.2
    hostname: client-{{ .Task.Slot }}
    networks:
      - ignite-net
    environment:
      NODE: CLIENT
      DISCOVERY: server-1
    ports:
      - target: 50001
        published: 50001
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - 'node.role == manager'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

