version: "3.2"

services:
  ignite-server:
    image: rainbow-storage:1.3.2-test
    network_mode: host
    environment:
      NODE: SERVER
      DISCOVERY: "ipv6"
      HOSTNAME: "ipv6"
#    volumes:
#      - "/opt/ignite-log4j.xml:/opt/assets/ignite-log4j.xml"
#      - ./data:/opt/assets/ignite
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 120s