version: "3.2"

networks:
  ignite-net:

services:
  ignite-server:
    image: ignite-server:1.0.0
    hostname: server-{{ .Task.Slot }}
    networks:
      - ignite-net
    environment:
      OPTION_LIBS: ignite-zookeeper
#      CONFIG_URI: XXXX
    ports:
#API Sockets
      - target: 50000
        published: 50000
        protocol: tcp
        mode: host
      - target: 50001
        published: 50001
        protocol: tcp
        mode: host
#Let thin clients connect
      - target: 10800
        published: 10800
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
        
  ignite-client:
    image: ignite-client:1.0.0
    hostname: client-{{ .Task.Slot }}
    networks:
      - ignite-net
    environment:
      OPTION_LIBS: ignite-zookeeper
#      CONFIG_URI: XXXX
    ports:
#API socket
      - target: 50002
        published: 50002
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - 'node.role == manager'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  zoo1:
    image: zookeeper:3.4
    hostname: zoo1
    networks:
      - ignite-net
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - 'node.role == manager'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

#  zoo2:
#    image: zookeeper:3.4
#    hostname: zoo2
#    networks:
#      - ignite-net
#    environment:
#      ZOO_MY_ID: 2
#      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888
#    ports:
#      - 2181:2181
#    deploy:
##      endpoint_mode: dnsrr
##      placement:
##          constraints:
##            - 'node.labels.myid == 2'
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 120s

