version: "3.2"

networks:
  ignite-net:

services:
  ignite-server:
    image: rainbow-storage:1.3.0
    hostname: server-{{ .Task.Slot }}
    networks:
      - ignite-net
    environment:
      NODE: SERVER
      DISCOVERY: ignite-server
      HOSTNAME: server-{{ .Task.Slot }}
#    volumes:
#      - ./data:/storage
    ports:
      - target: 50000
        published: 50000
        protocol: tcp
        mode: host
#      - target: 10800
#        published: 10800
#        protocol: tcp
#        mode: host
    deploy:
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

